com3_msgs:
  ubuntu:
  - ros-humble-com3-msgs
ic120_description:
  ubuntu:
  - ros-humble-ic120-description
ic120_msgs:
  ubuntu:
  - ros-humble-ic120-msgs
ic120_unity:
  ubuntu:
  - ros-humble-ic120-unity
ros_tcp_endpoint:
  ubuntu:
  - ros-humble-ros-tcp-endpoint
zx120_bringup:
  ubuntu:
  - ros-humble-zx120-bringup
zx120_control_hardware:
  ubuntu:
  - ros-humble-zx120-control-hardware
zx120_description:
  ubuntu:
  - ros-humble-zx120-description
zx120_unity:
  ubuntu:
  - ros-humble-zx120-unity
zx200_description:
  ubuntu:
  - ros-humble-zx200-description
zx200_manipulator_ikfast_plugin:
  ubuntu:
  - ros-humble-zx200-manipulator-ikfast-plugin
zx200_unity:
  ubuntu:
  - ros-humble-zx200-unity
gnss_localizer_ros2:
  ubuntu:
  - ros-humble-gnss-localizer-ros2
zx120_moveit_config:
  ubuntu:
  - ros-humble-zx120-moveit-config
zx200_control:
  ubuntu:
  - ros-humble-zx200-control
zx200_moveit_config:
  ubuntu:
  - ros-humble-zx200-moveit-config
ic120_navigation:
  ubuntu:
  - ros-humble-ic120-navigation
zx200_bringup:
  ubuntu:
  - ros-humble-zx200-bringup
zx200_navigation:
  ubuntu:
  - ros-humble-zx200-navigation
ic120_bringup:
  ubuntu:
  - ros-humble-ic120-bringup
